#!/usr/bin/env perl
#########################################################################
# Copyright (C) 2012  Wojciech Siewierski                               #
#                                                                       #
# This program is free software: you can redistribute it and/or modify  #
# it under the terms of the GNU General Public License as published by  #
# the Free Software Foundation, either version 3 of the License, or     #
# (at your option) any later version.                                   #
#                                                                       #
# This program is distributed in the hope that it will be useful,       #
# but WITHOUT ANY WARRANTY; without even the implied warranty of        #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
# GNU General Public License for more details.                          #
#                                                                       #
# You should have received a copy of the GNU General Public License     #
# along with this program.  If not, see <http://www.gnu.org/licenses/>. #
#########################################################################

#############################################################################
# NAME                                                                      #
#   webrun - transparent compatibility layer with http/https protocol       #
#                                                                           #
# SYNOPSIS                                                                  #
#   webrun gimp http://example.com/image.png                                #
#                                                                           #
# DESCRIPTION                                                               #
#   Prefix any command with "webrun" to automagically resolve any http URLs #
#   into the temporary files.                                               #
#                                                                           #
# DEPENDENCIES                                                              #
#   curl, zsh                                                               #
#############################################################################


use warnings;
use strict;

for (@ARGV) {
    $_ = "'$_'";
    $_ = "=(curl -s $_)" if m,^'https?://,;
}

exec("/bin/zsh", '-c', join(' ', @ARGV));
